import type { Metadata } from "next";
import Link from "next/link";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main>
      <div className="text-center">
        <Link href={"/"} className="text-blue-700 font-medium">
          Main
        </Link>
      </div>
      {children}
    </main>
  );
}
