import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="">
          <div className="m-20 flex items-center">
            <Link href={'/'}>
              <Image
                src={"/poke-logo.png"}
                alt="Logo"
                width={200}
                height={100}
              />
            </Link>
            <h1 className="text-5xl ml-9">Josmer Delgado Test</h1>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
